server:
  port: 8080

spring:
  application:
    name: db-switch-demo

  datasource:
    dbs:
      db1:
        urls:
          - jdbc:postgresql://localhost:5433/db1
          - jdbc:postgresql://localhost:5434/db1
          - jdbc:postgresql://localhost:5435/db1
        username: user
        password: pass
        driver-class-name: org.postgresql.Driver
      db2:
        urls:
          - jdbc:postgresql://localhost:5433/db2
          - jdbc:postgresql://localhost:5434/db2
          - jdbc:postgresql://localhost:5435/db2
        username: user
        password: pass
        driver-class-name: org.postgresql.Driver
    routing:
      leader-name: leader
      replica-name: replica

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

logging:
  config: classpath:logback.xml