services:
  replica-db0:
    image: postgres:latest
    container_name: replica-db0-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres_1
    ports:
      - "5433:5432"
    volumes:
      - replica-db0-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - db-network

  replica-db1:
    image: postgres:latest
    container_name: replica-db1-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres_2
    ports:
      - "5434:5432"
    volumes:
      - replica-db1-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - db-network

  replica-db2:
    image: postgres:latest
    container_name: replica-db2-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres_3
    ports:
      - "5435:5432"
    volumes:
      - replica-db2-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - db-network

volumes:
  replica-db0-data:
  replica-db1-data:
  replica-db2-data:

networks:
  db-network:
