@startuml
skinparam backgroundColor #FFFFFF
skinparam ArrowColor #005792
skinparam ActorFontColor #333333
skinparam ParticipantBackgroundColor #D6EAF8
skinparam ParticipantBorderColor #5DADE2
skinparam SequenceBoxBackgroundColor #EAECEE
skinparam SequenceBoxBorderColor #5DADE2
skinparam SequenceArrowColor #1ABC9C
skinparam SequenceDividerFontSize 16

title <b>Алгоритм работы системы переключения баз данных</b>
caption Оптимизация нагрузки на базы данных (Leader и Replica)

actor "Пользователь" as User #28B463

box "Приложение" #EAECEE
    participant "dsActivePool\n(Пул источников данных)" as Pool
    participant "Метод init()" as Init #58D68D
    participant "Метод close()" as Close #F1948A
    participant "Метод refresh()" as Refresh #F9E79F
    participant "Метод change()" as Change #5DADE2
end box

== Инициализация приложения ==

User -> Init: Старт приложения
Init -> Pool: Инициализация in-memory БД (H2)

== Закрытие неактуальных DataSource ==

User -> Close: Закрытие старых DataSource
Close -> Pool: Закрытие H2 и других неактуальных DataSource

== Создание новых DataSource ==

User -> Refresh: Обновление DataSource
Refresh -> Pool: Создание новых HikariDataSource для Leader и Replica

== Переключение DataSource ==

User -> Change: Переключение на Replica для чтения
Change -> Pool: Переключение с Leader на Replica (DataSource)

== Чтение данных ==

User -> Pool: Чтение данных из Replica
Pool --> User: Возвращает данные

@enduml
